### ISSUE TITLE
Huawei Gallery and others ANEs compatibility

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-HuaweiMobileServices#3]
Hi!

> This repository will form dependencies much like the GooglePlayServices repository for Google services. We are currently beta testing AppGallery integration into the InAppBilling extension and will be integrating Huawei Game Services into GameServices extension next.

It will be very helpfully to see this information in separate article anywhere in your site. And link this in your ANEs wiki. For example table of comparison between Google Market and Huawei Gallery in the context of your ANEs. And common questions such a what dependencies I need in both cases. Do I need have different manifest files for both markets? 
And what about other game important ANEs (Application, Push Notifications, Ads (IronSource), Firebase, ApplicationRater, Share)? Do they work in Huawei without modification?

May be you can include the same answers about Amazon Store.

Thx!

**Comment by marchbold** [comment]
This information is included when the ANE supports Huawei, currently this is only the InAppBilling ANE.

**Comment by Mintonist** [comment]
Ok, Firebase - is a Google service.

But does it mean that Share, Application, NetworkInfo, IronSource doesn't work on huawei devices?
If so seems we need to divide Android platform into two platforms in all ANEs descriptions.

**Comment by marchbold** [comment]
Huawei devices are still Android devices, so any extension that just uses android functionality will work without modification. 

The issue is the dependency on Google Play Services (GPS), which is google provided functionality and only available on approved devices. You can use the availability functionality in the Google Play Services client library to check for this.

These services are the only services that have been blocked on new Huawei devices, not standard Android functionality. In response, Huawei have introduced their own version of GPS, Huawei Mobile Services (HMS). 

So any extension that utilises GPS will most likely not work on new huawei devices that are missing GPS and will require an alternative implementation. However any extension like Application, Share, NetworkInfo that just use standard Android functionality will have no issues.

IronSource should still work as it is probably just the Google advertising id that it is using from GPS and it should function without it, however I haven't tested this and is probably a question for ironSource. AdMob mediation I'd expect to fail, and any of the ironSource mediators that rely on GPS. 

I don't understand your point about dividing into two platforms? I don't think that would be necessary. I think you would probably end up having a separate target for the Huawei app gallery, just as you probably have for the amazon or samsung stores currently, which would be your application without any google services.

**Comment by Mintonist** [comment]
Thx!
I just missed this information to understand the approach. May be you need add this somewhere in wiki.
